# Generated by Django 5.1.3 on 2024-11-29 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0002_remove_learner_mobile_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learner',
            name='subrole',
        ),
    ]
